name: CI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04  # Use a stable Ubuntu version

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3

      # Step 2: Install Subversion
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      # Step 3: Deploy using the deploy.sh script
      - name: Deploy
        run: chmod +x ./deploy.sh && ./deploy.sh
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
